repositories:
  olake:
    url: https://github.com/datazip-inc/olake.git
    branch: master
    enabled: true
    sync_frequency: hourly
  olake-ui:
    url: https://github.com/datazip-inc/olake-ui.git
    branch: master
    enabled: true
    sync_frequency: daily
  olake-helm:
    url: https://github.com/datazip-inc/olake-helm.git
    branch: master
    enabled: true
    sync_frequency: daily
  olake-docs:
    url: https://github.com/datazip-inc/olake-docs.git
    branch: master
    enabled: true
    sync_frequency: daily
  olake-fusion:
    url: https://github.com/datazip-inc/olake-fusion.git
    branch: master
    enabled: true
    sync_frequency: hourly
